WebApp/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class FormController : Controller
    {
        public ActionResult Form()
        {
            return View("FormPage", HttpContext.Application["forms"]);
        }

        [HttpPost]
        public ActionResult FormPage(string name, string genre,
            bool wantScifi, bool wantMobileVersion)
        {
            (HttpContext.Application["forms"] as List<(string, string, bool, bool)>)
                .Add((name, genre, wantScifi, wantMobileVersion));
            return RedirectToAction("FormPage");
        }

        [HttpGet]
        public ActionResult FormPage()
        {
            return View("FormPageResult", HttpContext.Application["forms"]);
        }


    }
}

WebApp/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class GuestController : Controller
    {
        [HttpGet]
        public ActionResult GuestPage()
        {
            return View(HttpContext.Application["reviews"]);
        }

        [HttpPost]
        public ActionResult AddReview(string name, string date, string text)
        {
            (HttpContext.Application["reviews"] as List<(string, string, string)>)
                .Add((name, date, text));
            return new RedirectResult("/Guest/GuestPage");
        }


    }
}

WebApp/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class MainController : Controller
    {
        public ActionResult MainPage()
        {
            return View(HttpContext.Application["articles"]);
        }

    }
}

WebApp/Views/Form/FormPage.cshtml
@{
    ViewBag.Title = "Form Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>

<div id="form">

    @using (Html.BeginForm("FormPage", "Form", FormMethod.Post))
    {
        <label>Enter your name</label>
            @Html.TextBox("name", "");
        <br />
        <p>Do you want more science fiction books?
            @Html.CheckBox("wantSciFi")
        </p>
        <br />
        <p>Do you want a version of this site for smartphones?
            @Html.CheckBox("wantMobileVersion", "")
        </p>
        <br />
        <ul>What literary genre do you prefer?</ul><br />
        <li> Fantastic @Html.RadioButton("genre", "Fantastic")</li><br />
        <li> Detectives @Html.RadioButton("genre", "Detectives")</li><br />
        <li> History @Html.RadioButton("genre", "History")</li><br />
        <li> Adventure @Html.RadioButton("genre", "Adventure")</li><br /><br />
        <input class="submit" type="submit" value="Send" />
    }
</div>

WebApp/Views/Form/FormPageResult.cshtml
﻿@using WebApp.ExtensionMethods

@{ ViewBag.Title = "Result of form";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@Html.DrawResults(Model as List<(string, string, bool, bool)>)

WebApp/Views/Guest/GuestPage.cshtml
﻿@{ ViewBag.Title = "Guest Page";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

<div id="reviews" class="col-md-offset-2">
    @foreach ((string name, string dateOfPublish, string text) a in Model)
    {
<div class="article">
    <p class="articleName">@a.name:</p>
    <p class="articleDate">@a.dateOfPublish</p>
    <p class="articleText">@a.text</p>
</div>}

    @using (Html.BeginForm("AddReview", "Guest", FormMethod.Post))
    {
      <input type="hidden" value=@DateTime.Now.ToShortDateString() name="date" />
     <p>Enter your name</p>
        @Html.TextBox("name", "", new { @class = "col-ms-12" });
     <p>Enter your review</p>
        @Html.TextArea("text", "", null);
     <input type="submit" class="submit" value="Send" />}
</div>

WebApp/Views/Main/About.cshtml
﻿@{ ViewBag.Title = "About"; }
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

WebApp/Views/Main/MainPage.cshtml
﻿@{ ViewBag.Title = "Main Page"; }

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@foreach ((string name, string dateOfPublish, string text) user in Model)
{
<div>
    <h2>@user.name</h2>
    <p>@user.dateOfPublish</p>
    <p>@user.text</p>
</div>}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href=@Url.Content("~/Content/Site.css") type="text/css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <main>
        <h1 class="text-center">
            <img alt="logo" src="~/logo.png" class="logo" />
            Library "Task23_Middle"
        </h1>
    </main>
    <div id="content" class="row">
        <div id="left" class="col-md-8">
            @RenderBody()
        </div>
        <div id="menu" class="col-md-2">
            <ul class="nav nav-stacked nav-pills text-center">
                <li><a href="/Main/MainPage">Main page</a></li>
                <li><a href="/Guest/GuestPage">Guest page</a></li>
                <li><a href="/Form/Form">Form page</a></li>
            </ul>
        </div>
    </div>
    <br />
    <footer>
        <script src="~/Scripts/up.js"></script>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>